version: '3.3' 
services:
  jenkins: 
    image: jenkins:jcasc  
    container_name: jenkins
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - JENKINS_ADMIN_ID=${ENV_JENKINS_ADMIN_ID} 
      - JENKINS_ADMIN_PASSWORD=${ENV_JENKINS_ADMIN_PASSWORD} 
      - GITLAB_USERNAME=${ENV_GITLAB_USERNAME}
      - GITLAB_PASSWORD=${ENV_GITLAB_PASSWORD}
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - ./casc.yaml:/var/jenkins_home/casc.yaml
      - /usr/bin/docker:/usr/bin/docker
volumes:
  jenkins-data:
